// content.js — Static content extracted from the original prototype.
window.AMANAT_CONTENT = {
  affirmations: [
    'Your feelings are not drama. They are information.',
    'You are allowed to take up space.',
    'Needing is not weakness. It is being human.',
    'You survived something that was not your fault.',
    'Patience can be a virtue. So can naming what happened.',
    'You do not owe your silence to anyone\u2019s comfort.',
    'Healing is not linear. Neither are you.',
    'The part of you that wanted better — that part was always right.',
    'Today, being here is enough.',
    'Rest is not a reward. It is a need.',
    'You are not too much. You are not the problem.',
  ],

  moodVocab: [
    { key: 'low',   label: 'Very low', glyph: '\u25CB', wash: '#f1d8d6' },
    { key: 'flat',  label: 'Numb',    glyph: '\u25D0', wash: '#e8e0c8' },
    { key: 'mixed', label: 'Mixed',   glyph: '\u25D1', wash: '#efe4cd' },
    { key: 'ok',    label: 'Okay',    glyph: '\u25D2', wash: '#d8e5d5' },
    { key: 'calm',  label: 'Calm',    glyph: '\u25D3', wash: '#e8efe1' },
    { key: 'safe',  label: 'Safe',    glyph: '\u25CF', wash: '#d0e2d6' },
  ],

  moodMessages: {
    low:   'It is okay to not be okay. You are still allowed to be here.',
    flat:  'Numb is also a feeling. You do not have to manufacture more.',
    mixed: 'Two true things can live in you at once.',
    ok:    'Okay is okay. You do not have to perform feeling better.',
    calm:  'If calm feels available, you can stay with it gently.',
    safe:  'Notice what is safe enough in this moment. Let your body check the room.',
  },

  bodyParts: [
    { id: 'head',     label: 'Head' },
    { id: 'jaw',      label: 'Jaw' },
    { id: 'throat',   label: 'Throat' },
    { id: 'chest',    label: 'Chest' },
    { id: 'stomach',  label: 'Stomach' },
    { id: 'shoulders',label: 'Shoulders' },
    { id: 'hands',    label: 'Hands' },
    { id: 'legs',     label: 'Legs' },
  ],

  whatsUp: [
    { id: 'someone-said',  label: 'Someone said something' },
    { id: 'flashback',     label: 'A memory came up' },
    { id: 'body-alarm',    label: 'My body is in alarm' },
    { id: 'argument',      label: 'An argument' },
    { id: 'work-pressure', label: 'Work or pressure' },
    { id: 'family',        label: 'Family' },
    { id: 'lonely',        label: 'Lonely' },
    { id: 'no-reason',     label: 'I don\u2019t know' },
  ],

  journalPrompts: [
    { key: 'body',       label: 'Body',       seed: 'Right now my body feels...' },
    { key: 'unsaid',     label: 'Unsaid',     seed: 'Something I have never said out loud is...' },
    { key: 'notice',     label: 'Noticed',    seed: 'Today I noticed...' },
    { key: 'understand', label: 'Understand', seed: 'What I want someone to understand is...' },
    { key: 'pride',      label: 'Pride',      seed: 'I am proud of myself for...' },
    { key: 'younger',    label: 'Younger me', seed: 'If I could write to my younger self I would say...' },
  ],

  supportModes: [
    {
      id: 'sit',
      title: 'Just sit with me',
      subtitle: 'No advice. No tools. No questions.',
      lines: [
        'I will stay with you for this minute.',
        'You do not have to explain anything.',
        'Let the screen be quiet. Let your body arrive at its own speed.',
      ],
    },
    {
      id: 'unsafe',
      title: 'I am not safe',
      subtitle: 'Physical safety before emotional grounding.',
      lines: [
        'Move toward people, light, an exit, a lock, or a public place if you can.',
        'Keep your phone with you. Avoid arguing through a door or in a room without an exit.',
        'Call a trusted person or emergency support now if danger may escalate.',
      ],
    },
    {
      id: 'public',
      title: 'Public place mode',
      subtitle: 'Silent, discreet grounding with neutral language.',
      lines: [
        'Press your toes down inside your shoes.',
        'Find three straight lines near you.',
        'Choose the next ordinary action: sip water, step outside, return to the task, or text one person.',
      ],
    },
    {
      id: 'family',
      title: 'Family pressure mode',
      subtitle: 'Guilt, honour, obedience, and emotional blackmail.',
      lines: [
        'Their shame is not proof that you did something wrong.',
        'Obedience is not the same as love.',
        'A boundary can be quiet: I cannot discuss this right now. I will come back later.',
      ],
    },
    {
      id: 'faith',
      title: 'Faith-sensitive mode',
      subtitle: 'Optional Islamic framing without preaching.',
      lines: [
        'Mercy matters here. Harm is not proof that Allah is punishing you.',
        'Your self is an amanah too.',
        'Zulm is not sabr. Seeking help is not weak faith.',
      ],
    },
  ],

  languageGuide: [
    { id: 'identity',  topic: 'Self and identity',
      threat: '\u201CI\u2019m broken.\u201D',
      safe:   '\u201CI\u2019m healing. I\u2019m learning.\u201D',
      note: 'Shame turns a wound into an identity. Safety separates the person from what happened.' },
    { id: 'minimise',  topic: 'Minimising harm',
      threat: '\u201CIt wasn\u2019t that bad.\u201D',
      safe:   '\u201CIt hurt me, even if others had it worse.\u201D',
      note: 'Minimising often began as protection. Naming impact is not exaggeration.' },
    { id: 'scanning',  topic: 'Threat scanning',
      threat: '\u201CWhen someone goes quiet, something bad is coming.\u201D',
      safe:   '\u201CSilence can sometimes just be silence.\u201D',
      note: 'Hypervigilance is the body trying to predict danger before it arrives.' },
    { id: 'needs',     topic: 'Needs and closeness',
      threat: '\u201CI don\u2019t need anything. I\u2019m fine.\u201D',
      safe:   '\u201CI have needs, and it\u2019s OK to name them.\u201D',
      note: 'Need can feel dangerous when care was unreliable or conditional.' },
    { id: 'flood',     topic: 'Emotional flooding',
      threat: '\u201CI feel everything at once and I can\u2019t stop it.\u201D',
      safe:   '\u201CThis feeling is intense, and it may shift with time and support.\u201D',
      note: 'Flooding is not drama. It is a nervous system state.' },
    { id: 'body',      topic: 'Body symptoms',
      threat: '\u201CThis pain is just me.\u201D',
      safe:   '\u201CMy body has been under chronic stress, and that is real.\u201D',
      note: 'The body can hold alarm long after the original threat is gone.' },
    { id: 'fawn',      topic: 'Fawn response',
      threat: '\u201CWhatever you think is fine.\u201D',
      safe:   '\u201CI have a perspective too. Would you like to hear it?\u201D',
      note: 'Appeasing can look like agreement, but it may be a survival response.' },
    { id: 'honour',    topic: 'Honour, sharam, and izzat',
      threat: '\u201CIf I speak, I will destroy the family.\u201D',
      safe:   '\u201CThe harm did not begin with me naming it.\u201D',
      note: 'Family honour pressure can make silence feel like duty. Truth-telling is not the original harm.' },
    { id: 'faith',     topic: 'Religious guilt',
      threat: '\u201CMaybe Allah is punishing me.\u201D',
      safe:   '\u201CSuffering is not proof that I deserved harm.\u201D',
      note: 'Faith-sensitive support can hold pain without preaching, blame, or forced certainty.' },
    { id: 'abandonment', topic: 'Abandonment trigger',
      threat: '\u201CA late reply means I am being left.\u201D',
      safe:   '\u201CMy alarm is real, and I can wait for more information.\u201D',
      note: 'Old attachment injuries can make ordinary distance feel like danger.' },
    { id: 'anger',     topic: 'Anger and revenge',
      threat: '\u201CI want them to suffer.\u201D',
      safe:   '\u201CMy anger is information. I can protect myself without becoming unsafe.\u201D',
      note: 'Anger can carry dignity. It still needs a route that does not create more harm.' },
    { id: 'csa',       topic: 'Childhood sexual abuse disclosure',
      threat: '\u201CAn uncle touched me when I was little. What if saying it ruins everything?\u201D',
      safe:   '\u201CWhat happened was not my fault. I deserve support that protects me.\u201D',
      note: 'A disclosure needs belief, privacy, consent, and safety planning before any pressure to confront or report.' },
    { id: 'all',       topic: 'All-or-nothing',
      threat: '\u201CEverything is ruined.\u201D',
      safe:   '\u201CThis part is hard right now.\u201D',
      note: 'Nuance comes back when the nervous system has enough safety to slow down.' },
  ],

  mindLoops: [
    { id: 'thought-danger',  topic: 'Thought danger',
      threat: '\u201CIf I think about it, I will fall apart.\u201D',
      safe:   '\u201CGradual, supported thinking can be tolerable.\u201D',
      note: 'A thought can be intense without being an emergency or an identity.' },
    { id: 'rumination',  topic: 'Rumination as protection',
      threat: '\u201CIf I keep analysing, I can prevent it from happening again.\u201D',
      safe:   '\u201CLearning patterns is different from endless replay.\u201D',
      note: 'Review can become a trap when it never returns the mind to the present.' },
    { id: 'worry',  topic: 'Worry as readiness',
      threat: '\u201CIf I stop worrying, something will go wrong.\u201D',
      safe:   '\u201CWorry does not control outcomes.\u201D',
      note: 'Care can exist without chronic alarm.' },
    { id: 'memory-doubt',  topic: 'Memory doubt',
      threat: '\u201CIf there are gaps, maybe none of it is real.\u201D',
      safe:   '\u201CGaps are common in trauma recall.\u201D',
      note: 'Imperfect memory does not automatically mean deception or exaggeration.' },
    { id: 'attention',  topic: 'Attention scanning',
      threat: '\u201CI have to monitor everything around me.\u201D',
      safe:   '\u201CAwareness can become flexible rather than constant.\u201D',
      note: 'Scanning may have helped before. It does not have to run everywhere forever.' },
    { id: 'suppression',  topic: 'Suppression pressure',
      threat: '\u201CI cannot let this enter my mind.\u201D',
      safe:   '\u201CGentle contact can be safer than forceful suppression.\u201D',
      note: 'Pushing thoughts away can sometimes make them rebound louder.' },
    { id: 'body-alarm',  topic: 'Body alarms',
      threat: '\u201CIf my heart is racing, I am unsafe.\u201D',
      safe:   '\u201CArousal can be stress, not danger.\u201D',
      note: 'Body sensations are information, not automatic predictions.' },
    { id: 'recovery',  topic: 'Recovery perfection',
      threat: '\u201CIf I still get triggered, I am not healed.\u201D',
      safe:   '\u201CHealing means more capacity, not zero symptoms.\u201D',
      note: 'A hard moment is data. It is not a verdict on recovery.' },
    { id: 'performance',  topic: 'Work as survival',
      threat: '\u201CIf I stop working, I collapse.\u201D',
      safe:   '\u201CRest may feel dangerous because stopping was never safe before.\u201D',
      note: 'Overworking can become a nervous-system strategy. Small pauses may need as much support as big changes.' },
    { id: 'options',  topic: 'Advice pressure',
      threat: '\u201CI need someone to tell me exactly what to do.\u201D',
      safe:   '\u201CI can look at options without handing my authority away.\u201D',
      note: 'Trauma can make decisions feel urgent. A good support gives choices, not commands.' },
  ],

  partnerScripts: [
    { id: 'disclosure', heading: 'When someone discloses abuse',
      text: 'I believe you. Thank you for trusting me with this. You did not deserve any of it.' },
    { id: 'triggered', heading: 'When someone is triggered',
      text: 'I can see this is a hard moment. Can we check what is safe around you right now? I am here.' },
    { id: 'hard-talk', heading: 'When you need a difficult conversation',
      text: 'I want to talk about something. Is now okay, or should we find a better time?' },
    { id: 'threat', heading: 'When the relationship feels threatened',
      text: 'There is no rush. We do not have to resolve this tonight. This is not about whether I care about you.' },
    { id: 'apology', heading: 'When they apologize for having feelings',
      text: 'You don\u2019t have to apologize for that. You are not too much. I\u2019m still here.' },
    { id: 'shutdown', heading: 'When they shut down',
      text: 'I notice you got quiet. I\u2019m not going anywhere. We can talk later, or just sit.' },
  ],

  partnerDos: [
    'Be consistent. Show up the same way, repeatedly.',
    'Ask what would help right now instead of assuming.',
    'Believe disclosures without making the person prove the pain.',
    'Name your actions before physical contact: \u201CI\u2019m going to touch your hand.\u201D',
    'Validate feelings before problem-solving.',
    'Encourage trauma-informed professional support without making care conditional.',
  ],
  partnerDonts: [
    'Do not say \u201Cjust let it go\u201D or \u201Cit was so long ago.\u201D',
    'Do not share a disclosure with anyone else.',
    'Do not interpret shutdown as punishment or manipulation.',
    'Do not escalate your voice or physical presence when someone is flooded.',
    'Do not threaten to leave during an argument.',
    'Do not expect linear progress. A hard day after a good day is not failure.',
  ],

  crisisSteps: [
    { id: 'active-danger', topic: 'Active danger at home', steps: [
      'Do not reassure with \u201Cyou are safe\u201D until safety is checked.',
      'Ask: \u201CAre they in the room? Can you move to a safer place or lock a door?\u201D',
      'Keep the phone charged and close. Avoid arguing through the door.',
      'Call a trusted person, neighbour, building guard, or emergency service if the threat may escalate.',
      'If there is immediate physical danger, call 1122, 15, or the nearest emergency support available.',
    ] },
    { id: 'self-harm', topic: 'Self-harm urges', steps: [
      'Say clearly: \u201CI want you alive tonight. Please do not stay alone with this.\u201D',
      'Move blades, pills, cords, weapons, or other means away from the person if it is safe to do so.',
      'Ask them to call or message one real person now and stay connected until the urge passes.',
      'Use delay language: \u201CFor the next 10 minutes, we only have to reduce access and stay here.\u201D',
      'If they may act soon, call emergency services or take them to the nearest emergency department.',
    ] },
    { id: 'dissociation', topic: 'Dissociation', steps: [
      'Lower your voice and slow your movements.',
      'Say the person\u2019s name calmly once.',
      'Name the date, the room, and one visible object: \u201CIt is today. You are in this room. I can see the door.\u201D',
      'Offer an anchor: water, a blanket, or a hand only if they allow it.',
      'Do not demand eye contact, a verbal response, or an explanation.',
      'Afterward say: \u201CThat was hard. You are back now. I am here.\u201D',
    ] },
    { id: 'flooding', topic: 'Emotional flooding', steps: [
      'Do not match the intensity. Your calm can be something steady they can borrow.',
      'Say: \u201CI can see you are overwhelmed. I am not going anywhere.\u201D',
      'Suggest a pause and agree when to return.',
      'Do not try to solve the argument while anyone is flooded.',
      'Reconnect warmly before resuming the hard topic.',
    ] },
    { id: 'suicide', topic: 'Suicidal thoughts', steps: [
      'Stay calm. Do not panic, withdraw, or shame the disclosure.',
      'Ask directly: \u201CAre you thinking about ending your life?\u201D',
      'Ask: \u201CAre you safe right now? Do you have a plan?\u201D',
      'If risk is immediate, call emergency services or go to the nearest emergency department.',
      'Do not leave the person alone until they are safe.',
    ] },
    { id: 'flashback', topic: 'Nightmares or flashbacks', steps: [
      'Do not touch without asking first.',
      'Say quietly: \u201CThat smell/sound/image is a memory signal. Let\u2019s find today\u2019s room.\u201D',
      'Let the person orient slowly.',
      'Offer the kind of comfort they usually accept: presence, warmth, or quiet.',
      'Check in later without forcing a full retelling.',
    ] },
    { id: 'csa-disclosure', topic: 'Childhood sexual abuse disclosure', steps: [
      'Believe first. Say: \u201CI believe you. It was not your fault.\u201D',
      'Do not ask for graphic details or push for confrontation.',
      'Ask what they need right now: privacy, medical care, a safe adult, legal advice, or quiet presence.',
      'If a child may currently be unsafe, prioritise protection and specialist support.',
      'Offer Pakistan resources such as Sahil, Rozan, Umang, or a trauma-informed clinician.',
    ] },
    { id: 'medical-red-flags', topic: 'Body pain and medical red flags', steps: [
      'Trauma can show up in the body, but new or severe symptoms deserve medical care.',
      'For chest pain, fainting, trouble breathing, heavy bleeding, sudden weakness, severe abdominal pain, or risk of poisoning, seek urgent medical help.',
      'If symptoms are familiar stress signals, use grounding while also tracking what changes.',
      'This app cannot tell whether a body symptom is medical or stress-related.',
    ] },
  ],

  resources: [
    { tag: 'crisis',   name: 'Umang Pakistan Helpline',
      desc: 'Free, confidential mental health helpline. Trained counsellors. Available daily.',
      contact: '0311-7786264', kind: 'tel', href: 'tel:03117786264', verified: 'Verified May 22, 2026 from Umang contact page.' },
    { tag: 'therapy',  name: 'PILL — Pakistan Institute of Living & Learning',
      desc: 'Culturally sensitive, evidence-based mental health care. Trauma-informed therapists. Lahore & Karachi.',
      contact: 'pill.org.pk', kind: 'link', href: 'https://pill.org.pk' },
    { tag: 'crisis',   name: 'Rozan Counselling',
      desc: 'Telephonic and in-person counselling. Islamabad-based with national outreach.',
      contact: '0304-111-1741', kind: 'tel', href: 'tel:03041111741', verified: 'Verified May 22, 2026 from Rozan counselling services page.' },
    { tag: 'crisis',   name: 'Rescue 1122',
      desc: 'Emergency medical, rescue, fire, and disaster response service in many parts of Pakistan.',
      contact: '1122', kind: 'tel', href: 'tel:1122', verified: 'Verified May 22, 2026 from Rescue 1122 official site.' },
    { tag: 'crisis',   name: 'Police emergency',
      desc: 'Police emergency contact for immediate physical danger.',
      contact: '15', kind: 'tel', href: 'tel:15', verified: 'Verified May 22, 2026 from Punjab Police emergency helplines page.' },
    { tag: 'therapy',  name: 'Aga Khan University Psychiatry',
      desc: 'Department of Psychiatry, AKUH. PTSD, cPTSD, anxiety and trauma treatment. Karachi.',
      contact: '021-111-911-911', kind: 'tel', href: 'tel:021111911911' },
    { tag: 'support',  name: 'Sahil',
      desc: 'Child protection and abuse prevention. Crisis support for families and survivors.',
      contact: 'sahil.org', kind: 'link', href: 'https://sahil.org' },
    { tag: 'crisis',   name: 'Edhi Foundation',
      desc: 'Nationwide ambulance and emergency support.',
      contact: '115', kind: 'tel', href: 'tel:115', verified: 'Verified May 22, 2026 from Punjab Police emergency helplines page.' },
    { tag: 'support',  name: 'Aangan Trust',
      desc: 'Child protection and family support in Lahore.',
      contact: '042-35761999', kind: 'tel', href: 'tel:04235761999' },
    { tag: 'therapy',  name: 'Emotionally Focused Therapy (EFT)',
      desc: 'The strongest evidence-based approach for couples where one partner carries attachment trauma.',
      contact: 'iceeft.com', kind: 'link', href: 'https://iceeft.com' },
  ],

  reframeExamples: [
    { in: 'No one really cares.', out: '"Right now I can\u2019t feel that anyone cares. The feeling is real. The conclusion may not be the whole truth."' },
    { in: 'I always ruin things.', out: '"This part is hard right now. \u2018Always\u2019 is the trauma talking, not the timeline."' },
  ],
};
